---
  - name: php-start
    service:
      name: php7.0-fpm
      state: started
    become: true
  
  - name: php-restart
    service:
      name: php7.0-fpm
      state: restarted
    become: true
  
  - name: php-stop
    service:
      name: php7.0-fpm
      state: stopped
    become: true
