---
  ######  Dotdeb.org  ######

  - name: Add dotdeb main
    apt_repository: repo='deb http://packages.dotdeb.org jessie all' state=present
  - name: Add dotdeb main src
    apt_repository: repo='deb-src http://packages.dotdeb.org jessie all' state=present

  - name: APT | Install DotDeb key
    apt_key: url='https://www.dotdeb.org/dotdeb.gpg' state=present
    tags: dotdeb
