---
  - include_vars: "vars/{{env}}.yml"

  - name: MySQL | Install MySQL
    apt: pkg={{ item }} state=installed force=yes
    with_items:
      - mysql-server
      - mysql-client
      - python-mysql.connector
      - python-mysqldb

  - name: MySQL | Set root password
    mysql_user: name=root password={{ root_password }} priv=*.*:ALL,GRANT state=present
    become: true

  - name: MySQL | Copy root password config to root user
    template: src="templates/my.cnf.j2" dest=/root/.my.cnf
    become: true

  - name: MySQL | Create dev user
    mysql_user: login_user=root login_password={{ root_password }} name={{ username }} password={{ password }} priv="*.*:ALL" state=present
    become: true

  - name: MySQL | Create development database
    mysql_db: name={{ database }}
    become: true

  - name: MySQL | Create test database
    mysql_db: name={{ test_database }}
    become: true
