---
  - name: nginx-start
    service:
      name: nginx
      state: started
      become: true
  
  - name: nginx-restart
    service:
      name: nginx
      state: restarted
      become: true
  
  - name: nginx-stop
    service:
      name: nginx
      state: stopped
      become: true
